# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NearCorona' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'DropDown'
pod 'VerticalSlidingPresentationController', '~> 0.1.3'
  # Pods for NearCorona

end
