# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherAppClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod "Gradients"
pod "Pastel"
pod 'ParallaxHeader', '~> 3.0.0'
  # Pods for WeatherAppClone

end
